### PR TITLE
Consent Updates

### PR DESCRIPTION
**Pull request by jakekrog**
This branch makes implements the following changes to the consent and onboarding process:
- Update graphics and animation for "We'll Test Your Understanding" screen
- Update UI and copy for "What to Expect" screen
- Use a tutorial alert instead of "All Set!" screen

### CODE REVIEW

**Comment by syoung-smallwisdom** [comment]
@jakekrog 

Unfortunately, we cannot accept this pull request.

The mPower app no longer uses the AppCore onboarding flow but there are other apps that _do_ still use this code. Changes of this nature require getting permission from the IRB as well as full QA _and_ Apple app review and there isn't time even if everyone who uses this repo wanted to include it in their submissions. Plus they were not implemented in a reverse-compatible way and are breaking changes to existing apps.

Please do resubmit the tutorial module as a stand-alone optional include, removing the part where you default the tutorial to being enabled. It's nice work.

**Comment by evliu** [comment]
Hey @syoung-smallwisdom ,

Re: Tutorial
The tutorial module is already stand-alone, so did you just want the call to display the tutorial removed and to keep the presentation controller and the tutorial view in AppCore?

**Comment by syoung-smallwisdom** [comment]
@evliu You have the tutorial lumped in with the the health kit prompt (which is NOT used by mPower). Additionally, you have 

```
NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
if (![defaults valueForKey:kShowTutorialEnabledKey]) {
    [defaults setBool:YES forKey:kShowTutorialEnabledKey];
}
```

in there twice. that is saying "hey, if the user defaults are not _EXPLICITLY_ set to `NO` then set it to `YES`.  There are apps that use this shared code other than mPower. Don't do this.

**Comment by evliu** [comment]
@syoung-smallwisdom  That's no problem at all. I can reverse the commits to only have the new presentation controller and the tutorial view controller classes so you can use them in the future. That way, the other classes won't be touched. Does that sound like a good plan of action? Thanks

**Comment by syoung-smallwisdom** [comment]
perfect!  thanks!

On Mon, Feb 29, 2016 at 4:34 PM, Everest Liu notifications@github.com
wrote:

> @syoung-smallwisdom https://github.com/syoung-smallwisdom That's no
> problem at all. I can reverse the commit to only have the new presentation
> controller and the tutorial view controller classes so you can use them in
> the future. That way, the other classes won't be touched. Does that sound
> like a good plan of action? Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Sage-Bionetworks/AppCore/pull/86#issuecomment-190468997
> .

## 

_Shannon Young_ | Senior Software Engineer |
Sage Bionetworks | 1100 Fairview Ave N, M1-C108 | Seattle, WA 98109 |
c: 206-335-8922 <206.335.8922> | e: shannon.young@sagebase.org

**Comment by Erin-Mounts** [comment]
Vector PDF assets are much preferred over png.

**Comment by evliu** [comment]
@Erin-Mounts We totally agree! I was following the convention already taken, and AppCore had pngs and I didn't want to create a new Images.xcassets if everything else was pngs, which a pdf vector would require. When we add images to the parent app where there is an .xcassets, then we always provide a pdf vector. Thanks for bringing it up.

**Comment by Erin-Mounts** [comment]
Ah, gotcha. Dang, we've got an ongoing project to have BridgeAppSDK and BridgeSDK take over AppCore's functions and then ditch AppCore altogether, and it'd have been much nicer to have vector PDFs for that. Oh well.

**Comment by syoung-smallwisdom** [comment]
closing

**Pull request closed without merging**
