### PR TITLE
Update Withdraw/Pause Study UX and internal implementation

### PR DESCRIPTION
**Pull request by Erin-Mounts**

### CODE REVIEW

**Comment by EricSiegNW** [comment]
A few things I noticed after refactor fix:

When I tap "pause study" and the pause process completes, the button still says "pause study" until I leave the tab and come back.
When I leave and come back, the "Resume Study" text doesn't fit, so it says "Resu...Study" which seems less optimal

Minor things:
When I leave and come back, the "Resume Study" button is now red background w/ White text. Is this intended? (My assumption is yes, but wanted to confirm)
The removed conditional in APCProfileViewController.m is commented out rather than deleted
The Sharing Options button in that same area doesn't have the same bracket and indent approach as the buttons above it.
I received the consent agreement email both when I pause the study and when I resume. Is that correct?

**Comment by Erin-Mounts** [comment]
Urgh, that's what I get for working late in the evening on Friday and not checking my work Monday morning. Should all be fixed. The consent agreement email is triggered on the back end by updating the sharing scope, so yeah.

**Comment by EricSiegNW** [comment]
Pause Study is not aligned with Leave Study above it. IIRC, this was aligned correctly before, might have lost alignment with other changes?

**Comment by EricSiegNW** [comment]
r=me

**Pull request merged**
