### PR TITLE
feature/BRIDGE-1054

### PR DESCRIPTION
**Pull request by dephillipsmichael**
Added the ability for json serialization to do custom formatting on dates of certain keys in the dictionary.

### CODE REVIEW

**Comment by syoung-smallwisdom** [comment]
I think it would be cleaner and less confusing to do one of two things:

(1) Change the class methods to instance methods on `APCJSONSerializer` and add a property for the `dateFormattersForKeys` dictionary.

-OR-

(2) Pass the `withDateFormattersForKeys: (NSDictionary*)  keyWithDateFormatter` down to the recursive levels.

Thanks.

**Comment by dephillipsmichael** [comment]
I think the more correct solution would be solution 1, as I originally looked at implementing solution 2 and it was a a mess of passing around arguments that 99% of the time are nil.

**Comment by dephillipsmichael** [comment]
Updated to switch APCJSONSerializer to favor more of an object instance implementation for the developer, especially when using the custom date formatter constructor.

**Comment by syoung-smallwisdom** [comment]
Better, thanks!

**Pull request merged**
